### ISSUE TITLE
截图全部挂了。

### ISSUE THREAD

**Issue by VincentSit** [Greedysky/TTKWidgetTools#3]
https://github.com/Greedysky/TTKWidgetTools/wiki/Screenshots

**Comment by Greedysky** [comment]
Fixed!

**Comment by VincentSit** [comment]
It looks like the last four images still can't be displayed.
![image](https://user-images.githubusercontent.com/4084679/55557330-3320d000-571c-11e9-92c3-a6ff310bd7da.png)

**Comment by Greedysky** [comment]
@VincentSit fixed, thx!
